"""Shadow AI detection: identify which AI tools are active in a repository.

Scans git history, file patterns, and commit metadata to detect AI tool
usage signatures. No network calls required — git-only mode by default.

Detected tools: Claude Code, Cursor, GitHub Copilot, Codex/ChatGPT, and
unknown LLM proxy endpoints referenced in .env history.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import TextIO


# ---------------------------------------------------------------------------
# Tool signatures
# ---------------------------------------------------------------------------

# File/directory presence signals
FILE_SIGNALS: dict[str, list[str]] = {
    "Claude Code": [
        "CLAUDE.md",
        ".claude/settings.json",
        ".claude/settings.local.json",
        ".claude/",
    ],
    "Cursor": [
        ".cursor/",
        ".cursor/rules",
        ".cursorrules",
        ".cursorignore",
    ],
    "GitHub Copilot": [
        ".github/copilot-instructions.md",
        ".copilot/",
    ],
    "Codex / ChatGPT": [
        "codex.md",
        ".openai/",
        "openai.json",
    ],
    "Windsurf": [
        ".windsurfrules",
        ".codeium/",
    ],
    "Aider": [
        ".aider.conf.yml",
        ".aider/",
        "aider.conf.yml",
    ],
}

# Commit message patterns that suggest AI tool usage
COMMIT_PATTERNS: dict[str, list[str]] = {
    "Claude Code": [
        r"\bClaude\b",
        r"claude-code",
        r"🤖.*claude",
    ],
    "GitHub Copilot": [
        r"Co-authored-by: GitHub Copilot",
        r"copilot suggestion",
    ],
    "Codex / ChatGPT": [
        r"generated by (chatgpt|gpt-4|openai)",
        r"Co-authored-by: ChatGPT",
    ],
    "Cursor": [
        r"cursor (ai|generated|suggested)",
    ],
}

# Known LLM API endpoint patterns (for .env history scanning)
LLM_ENDPOINT_PATTERNS: list[re.Pattern] = [
    re.compile(r"api\.anthropic\.com", re.I),
    re.compile(r"api\.openai\.com", re.I),
    re.compile(r"generativelanguage\.googleapis\.com", re.I),
    re.compile(r"api\.cohere\.ai", re.I),
    re.compile(r"api\.mistral\.ai", re.I),
    re.compile(r"openrouter\.ai", re.I),
    re.compile(r"together\.ai", re.I),
    re.compile(r"groq\.com/openai", re.I),
]

APPROVED_ENDPOINTS: dict[str, str] = {
    "api.anthropic.com": "Claude Code",
    "api.openai.com": "Codex / ChatGPT",
    "generativelanguage.googleapis.com": "Gemini",
}

# PII / proprietary data patterns
PII_PATTERNS: list[re.Pattern] = [
    re.compile(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"),  # email
    re.compile(r"\b\d{3}-\d{2}-\d{4}\b"),  # SSN-like
]


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class ToolDetection:
    tool_name: str
    confidence: str          # "confirmed" | "likely" | "possible"
    signals: list[str]       # human-readable evidence
    contributor_count: int = 0


@dataclass
class DataRiskIndicator:
    description: str
    commit_hash: str = ""
    file_path: str = ""


@dataclass
class AuditToolsReport:
    repo_path: str
    since: str
    approved_tools: list[str]
    detections: list[ToolDetection]
    unapproved_signals: list[str]
    data_risk_indicators: list[DataRiskIndicator]
    unknown_endpoints: list[str]


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def _git(repo: Path, *args: str, since: str = "") -> str:
    """Run a git command and return stdout. Returns '' on error."""
    cmd = ["git", "-C", str(repo)] + list(args)
    if since:
        # Insert --since before the first non-flag arg where appropriate
        pass
    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=30
        )
        return result.stdout
    except Exception:
        return ""


def _git_log(repo: Path, since: str, fmt: str, extra: list[str] | None = None) -> list[str]:
    args = ["log", f"--format={fmt}"]
    if since:
        args.append(f"--since={since}")
    if extra:
        args.extend(extra)
    out = _git(repo, *args)
    return [line for line in out.splitlines() if line.strip()]


def _git_contributors(repo: Path, since: str) -> set[str]:
    lines = _git_log(repo, since, "%ae")
    return set(lines)


def _file_exists_in_repo(repo: Path, patterns: list[str]) -> list[str]:
    """Return which of the given file/dir patterns exist in the repo."""
    found = []
    for pat in patterns:
        p = repo / pat
        if p.exists():
            found.append(pat)
    return found


def _scan_commit_messages(repo: Path, since: str, patterns: list[re.Pattern]) -> list[str]:
    """Return commit hashes where any pattern matches the commit message."""
    messages = _git_log(repo, since, "%H %s")
    hits = []
    for line in messages:
        parts = line.split(" ", 1)
        if len(parts) < 2:
            continue
        sha, msg = parts
        for pat in patterns:
            if pat.search(msg):
                hits.append(sha[:8])
                break
    return hits


def _scan_env_history(repo: Path, since: str) -> tuple[list[str], list[str]]:
    """Scan git history of .env files for LLM endpoint references.

    Returns (known_endpoints, unknown_endpoints).
    """
    # Get all commits that touched .env files
    log = _git_log(repo, since, "%H", ["--", "*.env", ".env", ".env.*"])
    known: list[str] = []
    unknown: list[str] = []

    for sha in log[:50]:  # cap at 50 commits for performance
        diff = _git(repo, "show", "--stat", sha)
        content = _git(repo, "show", f"{sha}:.env") or _git(repo, "show", f"{sha}:.env.example")
        if not content:
            continue
        for pat in LLM_ENDPOINT_PATTERNS:
            if pat.search(content):
                endpoint = pat.pattern.replace("\\.", ".").replace("\\b", "").replace("(", "").replace(")", "").split("|")[0]
                if any(ep in content for ep in APPROVED_ENDPOINTS):
                    known.append(endpoint)
                else:
                    unknown.append(endpoint)

    return list(set(known)), list(set(unknown))


def _scan_pii_in_commits(repo: Path, since: str) -> list[DataRiskIndicator]:
    """Look for PII patterns in recently committed files."""
    indicators: list[DataRiskIndicator] = []
    log = _git_log(repo, since, "%H", ["--diff-filter=A"])

    for sha in log[:30]:
        diff = _git(repo, "show", "--unified=0", sha)
        for line in diff.splitlines():
            if not line.startswith("+") or line.startswith("+++"):
                continue
            for pat in PII_PATTERNS:
                if pat.search(line):
                    indicators.append(DataRiskIndicator(
                        description=f"PII pattern found in commit {sha[:8]}",
                        commit_hash=sha[:8],
                    ))
                    break
        if len(indicators) >= 5:
            break

    return indicators


# ---------------------------------------------------------------------------
# Main detection logic
# ---------------------------------------------------------------------------

def detect_ai_tools(
    repo_path: str = ".",
    since: str = "90 days ago",
    approved: list[str] | None = None,
) -> AuditToolsReport:
    repo = Path(repo_path).resolve()
    approved_tools = [t.lower() for t in (approved or [])]

    detections: list[ToolDetection] = []

    for tool_name, file_patterns in FILE_SIGNALS.items():
        found_files = _file_exists_in_repo(repo, file_patterns)
        signals: list[str] = []
        confidence = ""

        if found_files:
            signals.extend(f"file present: {f}" for f in found_files)
            confidence = "confirmed"

        # Commit message scan
        commit_pats = [re.compile(p, re.I) for p in COMMIT_PATTERNS.get(tool_name, [])]
        if commit_pats:
            hits = _scan_commit_messages(repo, since, commit_pats)
            if hits:
                signals.append(f"commit message patterns in {len(hits)} commit(s)")
                if not confidence:
                    confidence = "likely"

        if signals:
            detections.append(ToolDetection(
                tool_name=tool_name,
                confidence=confidence or "possible",
                signals=signals,
            ))

    # Endpoint scanning
    known_eps, unknown_eps = _scan_env_history(repo, since)

    # Unapproved signals
    unapproved: list[str] = []
    for det in detections:
        if approved_tools and det.tool_name.lower() not in approved_tools:
            unapproved.append(f"{det.tool_name} detected but not in approved list")

    # Data risk
    data_risks = _scan_pii_in_commits(repo, since)

    return AuditToolsReport(
        repo_path=str(repo),
        since=since,
        approved_tools=approved or [],
        detections=detections,
        unapproved_signals=unapproved,
        data_risk_indicators=data_risks,
        unknown_endpoints=unknown_eps,
    )


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------

_CONFIDENCE_ICON = {
    "confirmed": "✅",
    "likely": "⚠️ ",
    "possible": "❓",
}


def format_audit_tools(report: AuditToolsReport, out: TextIO = sys.stdout) -> None:
    w = out.write
    sep = "─" * 55

    w(f"\nAI Tool Usage Report\n{sep}\n")
    w(f"Repo:  {report.repo_path}\n")
    w(f"Since: {report.since}\n")
    if report.approved_tools:
        w(f"Approved: {', '.join(report.approved_tools)}\n")
    w(f"{sep}\n")

    if report.detections:
        w("Detected tools:\n\n")
        for det in report.detections:
            icon = _CONFIDENCE_ICON.get(det.confidence, "❓")
            w(f"  {icon} {det.tool_name:<20} ({det.confidence})\n")
            for sig in det.signals[:3]:
                w(f"       {sig}\n")
        w(f"\n{sep}\n")
    else:
        w("No AI tool signatures detected.\n")

    if report.unapproved_signals:
        w("Unapproved tool signals:\n")
        for sig in report.unapproved_signals:
            w(f"  ❌ {sig}\n")
        w("\n")

    if report.unknown_endpoints:
        w("Unknown LLM endpoints in .env history:\n")
        for ep in report.unknown_endpoints:
            w(f"  ⚠️  {ep}\n")
        w("\n")

    if report.data_risk_indicators:
        w(f"Data risk indicators ({len(report.data_risk_indicators)}):\n")
        for risk in report.data_risk_indicators[:5]:
            w(f"  ⚠️  {risk.description}\n")
        w("\n")

    if not report.unapproved_signals and not report.unknown_endpoints and not report.data_risk_indicators:
        w("No unapproved tools or data risk indicators found.\n")

    w(f"{sep}\n\n")


# ---------------------------------------------------------------------------
# CLI handler
# ---------------------------------------------------------------------------

def cmd_audit_tools(args: argparse.Namespace) -> int:
    repo = getattr(args, "repo", ".") or "."
    since = getattr(args, "since", "90 days ago") or "90 days ago"
    approved_raw = getattr(args, "approved", "") or ""
    approved = [t.strip() for t in approved_raw.split(",") if t.strip()] if approved_raw else []

    report = detect_ai_tools(repo_path=repo, since=since, approved=approved)
    format_audit_tools(report)
    return 0
